### ISSUE TITLE
NoSuchMethodError received when using Spark 2.3.0

### ISSUE THREAD

**Issue by brandon-stanley** [AbsaOSS/ABRiS#136]
Hi Team, 

I am trying to get the ABRiS library working on a cluster running Spark 2.3.0. I have been able to successfully write to Confluent Kafka topics using Abris 3.2.0 on separate cluster running Spark 2.4.3. However, when I port the code over to another cluster running older version of Spark (2.3.0), I receive the following error:

```
Caused by: java.lang.NoSuchMethodError: org.apache.avro.Schema.createUnion([Lorg/apache/avro/Schema;)Lorg/apache/avro/Schema;
	at org.apache.spark.sql.avro.SchemaConverters$.toAvroType(SchemaConverters.scala:185)
	at org.apache.spark.sql.avro.SchemaConverters$$anonfun$5.apply(SchemaConverters.scala:176)
	at org.apache.spark.sql.avro.SchemaConverters$$anonfun$5.apply(SchemaConverters.scala:174)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:99)
	at org.apache.spark.sql.avro.SchemaConverters$.toAvroType(SchemaConverters.scala:174)
	at za.co.absa.abris.avro.sql.SchemaProvider$$anonfun$apply$2.apply(SchemaProvider.scala:93)
	at za.co.absa.abris.avro.sql.SchemaProvider$$anonfun$apply$2.apply(SchemaProvider.scala:91)
	at za.co.absa.abris.avro.sql.SchemaProvider.lazyLoadSchemas(SchemaProvider.scala:39)
	at za.co.absa.abris.avro.sql.SchemaProvider.unwrappedSchema(SchemaProvider.scala:51)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer$lzycompute(CatalystDataToAvro.scala:41)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer(CatalystDataToAvro.scala:40)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.nullSafeEval(CatalystDataToAvro.scala:44)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at org.apache.spark.sql.kafka010.KafkaWriteTask.execute(KafkaWriteTask.scala:45)
	at org.apache.spark.sql.kafka010.KafkaWriter$$anonfun$write$1$$anonfun$apply$1.apply$mcV$sp(KafkaWriter.scala:89)
	at org.apache.spark.sql.kafka010.KafkaWriter$$anonfun$write$1$$anonfun$apply$1.apply(KafkaWriter.scala:89)
	at org.apache.spark.sql.kafka010.KafkaWriter$$anonfun$write$1$$anonfun$apply$1.apply(KafkaWriter.scala:89)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.sql.kafka010.KafkaWriter$$anonfun$write$1.apply(KafkaWriter.scala:89)
	at org.apache.spark.sql.kafka010.KafkaWriter$$anonfun$write$1.apply(KafkaWriter.scala:87)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

I am guessing that this is related to the version of `spark-avro` that is being downloaded. Here is the `--packages` component of my `spark-submit` command:

```
--packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.3.0,za.co.absa:abris_2.11:3.2.0 --repositories https://packages.confluent.io/maven/
```

I noticed that there are no versions of [spark-avro](https://mvnrepository.com/artifact/org.apache.spark/spark-avro) for Spark 2.3.x but I see that there is [ABRiS documentation](https://github.com/AbsaOSS/ABRiS#supported-spark-versions) for Spark 2.3.x implying that it is possible to use ABRiS with Spark 2.3.x. The dependencies above download `org.apache.avro:avro:1.8.1` so the issue addressed in the [documentation](https://github.com/AbsaOSS/ABRiS#supported-spark-versions) regarding the version of avro does not seem to be the issue. Do you have any ideas on what the issue could be or what version of `spark-avro` should be used with Spark 2.3.0?

**Comment by cerveada** [comment]
Avro 1.8.1 has this method (createUnion) therefore it is not on the class path, otherwise this Exception could not happen.

You have to somehow overwrite the Avro version used by Spark 2.3. Maybe try to specify the avro directly in --packages?

**Comment by brandon-stanley** [comment]
Yeah, I have tried that as well, and I still get the error. I noticed that there are 2 avro packages:
1. [spark-avro](https://mvnrepository.com/artifact/org.apache.spark/spark-avro)
2. [avro](https://mvnrepository.com/artifact/org.apache.avro/avro)

The error above shows that the [spark-avro](https://github.com/apache/spark/blob/master/external/avro/src/main/scala/org/apache/spark/sql/avro/SchemaConverters.scala) library is what is making the call to `createUnion` which is in [avro](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.html) library. I noticed that there is not a version of [spark-avro](https://mvnrepository.com/artifact/org.apache.spark/spark-avro) for Spark 2.3.x. Could this be related to the issue?

**Comment by cerveada** [comment]
I think a way to solve this could be to declare Abris directly as a dependency of your application.
Do you use Maven or Sbt? Or something else?

**Comment by brandon-stanley** [comment]
Right now, I am just testing using `spark-submit` and the packages flag. I believe ivy is being used for dependencies.

**Comment by cerveada** [comment]
http://spark.apache.org/docs/latest/submitting-applications.html according to this you are supposed to create a "fat jar" from your application and submit it. 

Instead of using `--packages` you should declare Abris as your dependency in Ivy (or in something else you use) and then fat jar should contain Abris and Avro. So that should hopefully solve the problem.

**Comment by brandon-stanley** [comment]
I am submitting as a pyspark application and I believe the deployment pattern different

**Comment by cerveada** [comment]
The last thing that you could try is to build Abris fat jar and use it in --packages. There is a maven profile in pom.xml called `uber` that should do just that.

**Comment by brandon-stanley** [comment]
I was able to resolve the issue by specifying this flag in my `spark-submit` command: `--driver-class-path <PATH_TO_NEWER_AVRO_JAR>`. This resolution is odd because [this post](https://stackoverflow.com/questions/43257324/what-is-the-use-of-driver-class-path-in-the-spark-command) implies that the `--jars/--packages` flag (which is what I was using before) achieves the same goal as `--driver-class-path`. I am guessing that it has to do with a default jars (which includes the older avro jar) that are added to the classpath which must have been overriding the newer avro jar specified in `--packages/--jars`.

**Comment by cerveada** [comment]
Interesting, thanks for reporting back the solution.
